spring.application.name=EducationCrmProject

#database configurations
spring.datasource.url=jdbc:postgresql://localhost:5432/education_crm_db
spring.datasource.username=postgres
spring.datasource.password=root
server.port=9090
#hibernate configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true