spring.application.name=EducationCrmProject

#database configurations
spring.datasource.url=jdbc:postgresql://spring-postgres-db.cjssqwa2ktb9.eu-north-1.rds.amazonaws.com:5432/education_crm_db
spring.datasource.username=postgres
spring.datasource.password=Education123
server.port=9090
#hibernate configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true